databases:
  - name: bookmarks
    plan: free

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookmarks
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free